### ISSUE TITLE
Stop Wyvern giving an error on empty input file.

### ISSUE THREAD

**Issue by potanin** [wyvernlang/wyvern#107]
Currently Wyvern interpreter complains but python and javac both accept empty files without any output.

**Comment by JonathanAldrich** [comment]
Yes, we should fix this.  Maybe allow the parser to accept the empty input, and generate "unit" as the program in that case?

**Comment by craigthelinguist** [comment]
Is an "empty" script with imports valid? Take the following example:

```
// firstModule.wyv
import secondModule
```

```
// secondModule.wyv
5
```
If I run `firstModule` I get `ToolError: Parse Error: Encountered "<EOF>" at line 0, column 0.`

**Comment by JonathanAldrich** [comment]
Hmm, not sure what semantics that should have.  I guess do the import and terminate (returning unit, to the extent that it matters)?

I think the current parser wants some declaration so it can choose between a module and a script.  I added a special case for empty files, but not for imports I guess.  That could be fixed with an additional tweak.

**Comment by craigthelinguist** [comment]
> Hmm, not sure what semantics that should have. I guess do the import and terminate (returning unit, to the extent that it matters)?

Yeah that's what I thought it should do as well. I've put this into a separate issue.
