### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [wyvernlang/wyvern#28]
Can this be licensed under a more permissive license like ASL 2.0.

**Comment by RobbieMcKinstry** [comment]
I would humbly suggest MIT, since ASL 2.0 is not compatible with GPL 2. Duel-licensing is also reasonable. :)

**Comment by potanin** [comment]
Can someone please explain a bit more why not GPL?

**Comment by JonathanAldrich** [comment]
I'm happy remaining with GPL unless there's a compelling case to change the license, but if someone came up with a good argument that the research (or language) would advanced better with a more permissive license I would consider it.  My first choice would be to move to LGPL, which would allow the Wyvern tools to be integrated into commercial products, but not to become proprietary themselves.  I'd consider MIT but as Robbie says ASL isn't a great option due to GPL incompatibility.

Maybe we should ask contributors to the project if they're OK going to LGPL (or even MIT) at some point in the future if the project leadership believes it's the right thing for the language.
