### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by RobbieMcKinstry** [wyvernlang/wyvern#42]
The document @JonathanAldrich authored for our meeting on Friday (10/16/15) has a small error in the path to the parser.

The document, under Section 4 `Parsing`, says in the first sentence of the second paragraph that the parser is implemented at `tools/src/wyvern/tools/coreparser/WyvernParser.jj`, though at least on `master` the actual location is `tools/src/wyvern/tools/parsing/coreparser/Wyvern`. A fairly innocuous typos, of course. I'll PR the change if no one gets to it first. Just opening the issue so I don't forget ^.^

**Comment by JonathanAldrich** [comment]
Hi Robbie,

Actually, if you are looking at tools/src/wyvern/tools/parsing/Wyvern.x, then you found our old parser.  That's the one that was implemented in copper, but because it merged all the parsing and all the lexing, it was pretty hard to debug.  We've replaced it with wyvern.tools.lexing.WyvernLexer.x for the lexer and wyvern.toools.parsing.coreparser.WyvernParser.jj for the parser.

If you want to make a note of this in the documentation, please go ahead, but make the note say that Wyvern.x is deprecated.  Thanks!

**Comment by RobbieMcKinstry** [comment]
Whoops! I meant to type `WyvernParser.jj`! I'm particularly glad you commented anyway, because now I know I didn't hack on the old parser yesterday! :)
